//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooKeeper.WebUI.ZookeeperWebSvc {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZookeeperDTO", Namespace="http://schemas.datacontract.org/2004/07/ZooKeeper.WebSvc.DTO")]
    [System.SerializableAttribute()]
    public partial class ZookeeperDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffID {
            get {
                return this.StaffIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffIDField, value) != true)) {
                    this.StaffIDField = value;
                    this.RaisePropertyChanged("StaffID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnimalDTO", Namespace="http://schemas.datacontract.org/2004/07/ZooKeeper.WebSvc.DTO")]
    [System.SerializableAttribute()]
    public partial class AnimalDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnimalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AnimalTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ZooKeeper.WebUI.ZookeeperWebSvc.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StaffIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnimalID {
            get {
                return this.AnimalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AnimalIDField, value) != true)) {
                    this.AnimalIDField = value;
                    this.RaisePropertyChanged("AnimalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnimalType {
            get {
                return this.AnimalTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.AnimalTypeField, value) != true)) {
                    this.AnimalTypeField = value;
                    this.RaisePropertyChanged("AnimalType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ZooKeeper.WebUI.ZookeeperWebSvc.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NickName {
            get {
                return this.NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.NickNameField, value) != true)) {
                    this.NickNameField = value;
                    this.RaisePropertyChanged("NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StaffID {
            get {
                return this.StaffIDField;
            }
            set {
                if ((object.ReferenceEquals(this.StaffIDField, value) != true)) {
                    this.StaffIDField = value;
                    this.RaisePropertyChanged("StaffID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/ZooKeeper.WebSvc.DTO")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZookeeperWebSvc.IZooKeeperService")]
    public interface IZooKeeperService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/GetZookepers", ReplyAction="http://tempuri.org/IZooKeeperService/GetZookepersResponse")]
        ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO[] GetZookepers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/GetZookepers", ReplyAction="http://tempuri.org/IZooKeeperService/GetZookepersResponse")]
        System.Threading.Tasks.Task<ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO[]> GetZookepersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/SaveZookeper", ReplyAction="http://tempuri.org/IZooKeeperService/SaveZookeperResponse")]
        void SaveZookeper(ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO zookeeperDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/SaveZookeper", ReplyAction="http://tempuri.org/IZooKeeperService/SaveZookeperResponse")]
        System.Threading.Tasks.Task SaveZookeperAsync(ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO zookeeperDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/DeleteZookeper", ReplyAction="http://tempuri.org/IZooKeeperService/DeleteZookeperResponse")]
        void DeleteZookeper(string staffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/DeleteZookeper", ReplyAction="http://tempuri.org/IZooKeeperService/DeleteZookeperResponse")]
        System.Threading.Tasks.Task DeleteZookeperAsync(string staffId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/GetAnimals", ReplyAction="http://tempuri.org/IZooKeeperService/GetAnimalsResponse")]
        ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO[] GetAnimals();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/GetAnimals", ReplyAction="http://tempuri.org/IZooKeeperService/GetAnimalsResponse")]
        System.Threading.Tasks.Task<ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO[]> GetAnimalsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/SaveAnimal", ReplyAction="http://tempuri.org/IZooKeeperService/SaveAnimalResponse")]
        void SaveAnimal(ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO animalDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/SaveAnimal", ReplyAction="http://tempuri.org/IZooKeeperService/SaveAnimalResponse")]
        System.Threading.Tasks.Task SaveAnimalAsync(ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO animalDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/DeleteAnimal", ReplyAction="http://tempuri.org/IZooKeeperService/DeleteAnimalResponse")]
        void DeleteAnimal(string animalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IZooKeeperService/DeleteAnimal", ReplyAction="http://tempuri.org/IZooKeeperService/DeleteAnimalResponse")]
        System.Threading.Tasks.Task DeleteAnimalAsync(string animalId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IZooKeeperServiceChannel : ZooKeeper.WebUI.ZookeeperWebSvc.IZooKeeperService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZooKeeperServiceClient : System.ServiceModel.ClientBase<ZooKeeper.WebUI.ZookeeperWebSvc.IZooKeeperService>, ZooKeeper.WebUI.ZookeeperWebSvc.IZooKeeperService {
        
        public ZooKeeperServiceClient() {
        }
        
        public ZooKeeperServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZooKeeperServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZooKeeperServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZooKeeperServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO[] GetZookepers() {
            return base.Channel.GetZookepers();
        }
        
        public System.Threading.Tasks.Task<ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO[]> GetZookepersAsync() {
            return base.Channel.GetZookepersAsync();
        }
        
        public void SaveZookeper(ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO zookeeperDTO) {
            base.Channel.SaveZookeper(zookeeperDTO);
        }
        
        public System.Threading.Tasks.Task SaveZookeperAsync(ZooKeeper.WebUI.ZookeeperWebSvc.ZookeeperDTO zookeeperDTO) {
            return base.Channel.SaveZookeperAsync(zookeeperDTO);
        }
        
        public void DeleteZookeper(string staffId) {
            base.Channel.DeleteZookeper(staffId);
        }
        
        public System.Threading.Tasks.Task DeleteZookeperAsync(string staffId) {
            return base.Channel.DeleteZookeperAsync(staffId);
        }
        
        public ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO[] GetAnimals() {
            return base.Channel.GetAnimals();
        }
        
        public System.Threading.Tasks.Task<ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO[]> GetAnimalsAsync() {
            return base.Channel.GetAnimalsAsync();
        }
        
        public void SaveAnimal(ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO animalDTO) {
            base.Channel.SaveAnimal(animalDTO);
        }
        
        public System.Threading.Tasks.Task SaveAnimalAsync(ZooKeeper.WebUI.ZookeeperWebSvc.AnimalDTO animalDTO) {
            return base.Channel.SaveAnimalAsync(animalDTO);
        }
        
        public void DeleteAnimal(string animalId) {
            base.Channel.DeleteAnimal(animalId);
        }
        
        public System.Threading.Tasks.Task DeleteAnimalAsync(string animalId) {
            return base.Channel.DeleteAnimalAsync(animalId);
        }
    }
}
